# Generated by Django 3.2.4 on 2021-06-14 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='上映时间'),
        ),
    ]
